# Generated by Django 4.0.3 on 2022-09-26 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aliasconxion', models.CharField(max_length=30)),
                ('comentariobd', models.TextField(max_length=150)),
                ('nomhost', models.CharField(max_length=100)),
                ('nompuerto', models.IntegerField()),
                ('nombd', models.CharField(max_length=80)),
                ('usuario', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=150)),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='schema_gr',
            fields=[
                ('id_m', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('id_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargasemantica.metadatos')),
            ],
        ),
    ]
