# Generated by Django 4.0.3 on 2022-03-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargasemantica', '0002_alter_metadatos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('detalleserror', models.CharField(max_length=500)),
            ],
        ),
    ]
