# Generated by Django 4.0.3 on 2022-04-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargasemantica', '0003_soporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soporte',
        ),
    ]
