# Generated by Django 4.0.3 on 2022-04-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargasemantica', '0005_metadatos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadatos',
            name='user',
        ),
    ]
