# Generated by Django 4.0.3 on 2022-04-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_soporte_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soporte',
            options={'verbose_name': 'Soportes'},
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='user',
        ),
    ]
