# Generated by Django 4.0.3 on 2022-08-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_soporte_iduser_soporte_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soporte',
            name='iduser',
        ),
    ]
