# Generated by Django 4.0.3 on 2022-09-26 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0003_remove_soporte_iduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soporte',
            options={'verbose_name': 'Soporte'},
        ),
        migrations.AddField(
            model_name='soporte',
            name='iduser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
